#!/usr/bin/env bash
# write-proposal-sh.sh — generate ./proposal.sh: every `cast send` needed to
# submit a MultichainGovernorV2 proposal, in order, from one forge-script run.
#
# The append calls are encoded against the predicted id (governor
# proposalCount()+1 on Ethereum, or BATCH_PROPOSAL_ID if exported), so there is
# no submit -> read id -> regenerate loop. proposal.sh re-checks proposalCount
# after call 1 and stops before appending if the prediction was wrong.
#
# Usage:
#   ./script/proposals/write-proposal-sh.sh proposals/mips/mip-x67/x67.sh [out.sh]
#   make proposal-sh MIP=mip-x67
#
# Env:
#   CAST_ACCOUNT  keystore account for cast send (default: moonwell)
#   CAST_RPC      rpc alias/url for cast send (default: ethereum)
#   .env is sourced for the fork RPC URLs forge needs.
#
# Requires: bash, forge, jq.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

ENV_SH="${1:?usage: write-proposal-sh.sh <mip .sh> [out.sh]}"
OUT="${2:-proposal.sh}"
CAST_ACCOUNT="${CAST_ACCOUNT:-moonwell}"
CAST_RPC="${CAST_RPC:-ethereum}"

[ -f "$ENV_SH" ] || { echo "ERROR: $ENV_SH not found" >&2; exit 1; }
[ -f .env ] && { set -a; . ./.env; set +a; }
# shellcheck disable=SC1090
. "$ENV_SH" >/dev/null

GOV="$(jq -r '.[] | select(.name=="MULTICHAIN_GOVERNOR_V2_PROXY") | .addr' chains/1.json)"
[ -n "$GOV" ] || { echo "ERROR: MULTICHAIN_GOVERNOR_V2_PROXY missing from chains/1.json" >&2; exit 1; }

# the template to run: a rewards MIP exports MIP_REWARDS_PATH; anything else
# registered against a template artifact must export TEMPLATE explicitly
TEMPLATE="${TEMPLATE:-}"
if [ -z "$TEMPLATE" ]; then
  if [ -n "${MIP_REWARDS_PATH:-}" ]; then
    TEMPLATE=proposals/templates/RewardsDistributionV2.sol
  else
    dir="$(dirname "$ENV_SH")"
    TEMPLATE="$(ls "$dir"/*.sol 2>/dev/null | head -n1 || true)"
  fi
fi
[ -n "$TEMPLATE" ] || { echo "ERROR: cannot infer the proposal .sol; export TEMPLATE=" >&2; exit 1; }

echo "running $TEMPLATE (DO_PRINT) ..." >&2
LOG="$(mktemp)"
DO_BUILD=true DO_RUN=false DO_VALIDATE=false DO_PRINT=true \
  forge script "$TEMPLATE" -vv >"$LOG" 2>&1 || { cat "$LOG" >&2; echo "ERROR: forge script failed" >&2; exit 1; }
grep -q "Script ran successfully" "$LOG" || { cat "$LOG" >&2; echo "ERROR: script did not finish" >&2; exit 1; }

# batched section: init (0xf2725649) then appends (0xd5eae5ab); else the
# single propose() calldata printed under "Proposal Calldata"
mapfile -t CALLS < <(awk '/Batched Proposal Calldata/{f=1} f && /^[[:space:]]*0x[0-9a-f]{8,}$/{gsub(/[[:space:]]/,""); print}' "$LOG")
BATCHED=1
if [ "${#CALLS[@]}" -eq 0 ]; then
  BATCHED=0
  mapfile -t CALLS < <(awk '/Proposal Calldata/{f=1} f && /^[[:space:]]*0x[0-9a-f]{8,}$/{gsub(/[[:space:]]/,""); print; exit}' "$LOG")
fi
[ "${#CALLS[@]}" -gt 0 ] || { cat "$LOG" >&2; echo "ERROR: no calldata found in output" >&2; exit 1; }
rm -f "$LOG"

N="${#CALLS[@]}"
# the id the appends were encoded against: word 0 of the first append call
# (propose(uint256 proposalId, ...)); console labels are not relied on
PREDICTED=""
if [ "$BATCHED" -eq 1 ] && [ "$N" -gt 1 ]; then
  PREDICTED=$((16#${CALLS[1]:10:64}))
fi
{
  echo '#!/bin/bash'
  echo "# generated by script/proposals/write-proposal-sh.sh from $ENV_SH"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not edit; regenerate instead"
  echo 'set -euo pipefail'
  echo "GOV=$GOV"
  echo "ACCOUNT=\${CAST_ACCOUNT:-$CAST_ACCOUNT}"
  echo "RPC=\${CAST_RPC:-$CAST_RPC}"
  echo
  if [ "$BATCHED" -eq 1 ]; then
    echo "EXPECTED_ID=${PREDICTED:-0}"
    echo 'echo "call 1 of '"$N"' - init (finalize=false); expected proposal id $EXPECTED_ID"'
    echo 'cast send "$GOV" --account "$ACCOUNT" --rpc-url "$RPC" \'
    echo "${CALLS[0]}"
    echo
    echo '# appends are encoded against EXPECTED_ID; stop if the init landed as another id'
    echo 'COUNT=$(cast call "$GOV" "proposalCount()(uint256)" --rpc-url "$RPC")'
    echo '[ "$COUNT" = "$EXPECTED_ID" ] || { echo "proposalCount=$COUNT != $EXPECTED_ID: STOP. export BATCH_PROPOSAL_ID=$COUNT and regenerate"; exit 1; }'
    for ((i = 1; i < N; i++)); do
      echo
      if [ "$i" -eq $((N - 1)) ]; then
        echo 'echo "call '"$((i + 1))"' of '"$N"' - append + finalize"'
      else
        echo 'echo "call '"$((i + 1))"' of '"$N"' - append (finalize=false)"'
      fi
      echo 'cast send "$GOV" --account "$ACCOUNT" --rpc-url "$RPC" \'
      echo "${CALLS[$i]}"
    done
  else
    echo 'echo "single propose() call"'
    echo 'cast send "$GOV" --account "$ACCOUNT" --rpc-url "$RPC" \'
    echo "${CALLS[0]}"
  fi
} >"$OUT"
chmod +x "$OUT"

if [ "$BATCHED" -eq 1 ]; then
  echo "wrote $OUT: $N calls (init + $((N - 1)) appends), expected proposal id ${PREDICTED:-?}" >&2
else
  echo "wrote $OUT: 1 call (not batched)" >&2
fi
