#!/bin/bash
export MTOKENS_PATH=proposals/mips/mip-x03/MTokens.json
echo "MTOKENS_PATH=$MTOKENS_PATH"

export EMISSION_CONFIGURATIONS_PATH=proposals/mips/mip-x03/RewardStreams.json
echo "EMISSION_CONFIGURATIONS_PATH=$EMISSION_CONFIGURATIONS_PATH"

export DESCRIPTION_PATH=proposals/mips/mip-x03/MIP-X03.md
echo "DESCRIPTION_PATH=$DESCRIPTION_PATH"

export PRIMARY_FORK_ID=0
echo "PRIMARY_FORK_ID=$PRIMARY_FORK_ID"

