
#!/bin/bash
export MTOKENS_PATH=src/proposals/mips/mip-b17/MTokens.json
echo "MTOKENS_PATH=$MTOKENS_PATH"

export EMISSION_CONFIGURATIONS_PATH=src/proposals/mips/mip-b17/RewardStreams.json
echo "EMISSION_CONFIGURATIONS_PATH=$EMISSION_CONFIGURATIONS_PATH"

export DESCRIPTION_PATH=src/proposals/mips/mip-b17/MIP-B17.md
echo "DESCRIPTION_PATH=$DESCRIPTION_PATH"

export PRIMARY_FORK_ID=1
echo "PRIMARY_FORK_ID=$PRIMARY_FORK_ID"

export EXCLUDE_MARKET_ADD_CHECKER=true
echo "EXCLUDE_MARKET_ADD_CHECKER=$EXCLUDE_MARKET_ADD_CHECKER"

export NONCE=0
echo "NONCE=$NONCE"



