#!/bin/bash
set -e

# MIP-X40 Deployment Script
# Generated by moonwell-rewards-slack-bot

source .env

export PROPOSAL_NAME="MIP-X40"
export PROPOSAL_PATH="proposals/mips/mip-x40/x40.json"

echo "Deploying $PROPOSAL_NAME..."

# Run the forge script for rewards distribution
forge script proposals/templates/RewardsDistribution.sol \
  --rpc-url $RPC_URL \
  --broadcast \
  --verify

echo "Deployment complete for $PROPOSAL_NAME"
