//SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.19;

import "@utils/ChainIds.sol";

import {RewardsDistributionV2Template} from "@proposals/templates/RewardsDistributionV2.sol";
import {AllChainAddresses as Addresses} from "@proposals/Addresses.sol";
import {ActionType} from "@proposals/proposalTypes/IProposal.sol";

interface IStakedWellCooldown {
    function COOLDOWN_SECONDS() external view returns (uint256);

    function UNSTAKE_WINDOW() external view returns (uint256);

    function EMISSION_MANAGER() external view returns (address);
}

/// @title MIP-X62
/// @notice Monthly rewards distribution generated by the reward-automation
///         worker and executed through the RewardsDistributionV2Template
///         (Ethereum-hub governance). The template auto-computes the
///         wormhole chunking and batched propose() submission — no
///         hand-tuned boundaries.
///
///         In addition to the monthly rewards, this proposal zeroes the
///         stkWELL withdrawal cooldown on Moonbeam (7 days -> 0) as part
///         of the Moonbeam wind-down: stakers can activate their cooldown
///         and redeem immediately instead of waiting a week. The unstake
///         window (2 days) is left unchanged. setCoolDownSeconds is gated
///         by onlyEmissionsManager and the EMISSION_MANAGER of the Moonbeam
///         stkWELL is the Temporal Governor, which executes this proposal's
///         Moonbeam actions.
contract mipx62 is RewardsDistributionV2Template {
    using ChainIds for uint256;

    /// @notice the live Moonbeam stkWELL cooldown this proposal removes;
    /// asserted in build so silent drift fails the simulation loudly
    uint256 public constant CURRENT_COOLDOWN_SECONDS = 7 days;

    function name() external pure override returns (string memory) {
        return "MIP-X62";
    }

    function build(Addresses addresses) public override {
        super.build(addresses);

        vm.selectFork(MOONBEAM_FORK_ID);
        address stkWell = addresses.getAddress("STK_GOVTOKEN_PROXY");

        assertEq(
            IStakedWellCooldown(stkWell).EMISSION_MANAGER(),
            addresses.getAddress("TEMPORAL_GOVERNOR"),
            "stkWELL emission manager must be the Temporal Governor"
        );

        assertEq(
            IStakedWellCooldown(stkWell).COOLDOWN_SECONDS(),
            CURRENT_COOLDOWN_SECONDS,
            "stkWELL cooldown drifted from the expected 7 days"
        );

        _pushAction(
            stkWell,
            abi.encodeWithSignature("setCoolDownSeconds(uint256)", 0),
            "Set the stkWELL withdrawal cooldown to 0 on Moonbeam (wind-down)",
            ActionType.Moonbeam
        );
    }

    function validate(Addresses addresses, address deployer) public override {
        super.validate(addresses, deployer);

        vm.selectFork(MOONBEAM_FORK_ID);
        IStakedWellCooldown stkWell = IStakedWellCooldown(
            addresses.getAddress("STK_GOVTOKEN_PROXY")
        );

        assertEq(
            stkWell.COOLDOWN_SECONDS(),
            0,
            "stkWELL cooldown must be 0 after X62"
        );

        assertEq(
            stkWell.UNSTAKE_WINDOW(),
            2 days,
            "stkWELL unstake window must be unchanged"
        );
    }
}
