//SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.19;

import {RewardsDistributionV2Template} from "@proposals/templates/RewardsDistributionV2.sol";

/// @title MIP-X65
/// @notice Monthly rewards distribution for the 2026-08-15 -> 2026-09-15
///         epoch, generated by the reward-automation worker and executed
///         through the RewardsDistributionV2Template (Ethereum-hub
///         governance). The template auto-computes the wormhole chunking
///         and the batched propose() submission from the encoded calldata,
///         so no hand-tuned chunk boundaries are needed here.
///
///         Unlike MIP-X62, this epoch carries NO Moonbeam actions: the
///         Moonbeam wind-down is complete, so the worker emits an empty
///         setRewardSpeed list and a zero stkWELL emission rate for 1284.
///         Ethereum, Base and Optimism follow the usual shape: fund from
///         FOUNDATION_MULTISIG on the hub, bridge to the Base Temporal
///         Governor, then set MRD speeds and create the Base merkle
///         campaigns.
contract mipx65 is RewardsDistributionV2Template {
    function name() external pure override returns (string memory) {
        return "MIP-X65";
    }
}
