name: Base Integration Tests - Part 2

on: [pull_request]

env:
    BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}

jobs:
  run-base-tests:
    name: base-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Base Mainnet Integration Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 10
           max_attempts: 3
           command: time forge test --match-contract LiveSystemBaseTest --fork-url base -vvv --ffi

