name: Foundry eth integration tests

on: [pull_request]

env:
  ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}

jobs:
  run-eth-mainnet-tests:
    name: eth-mainnet-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Integration Test Contracts
        run: time forge test --match-contract IntegrationTest --fork-url $ETH_RPC_URL
