name: Invariant Tests

on: [pull_request]

jobs:
  invariant-tests:
    name: invariant-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Invariant Test Contracts
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 15
           max_attempts: 3
           command: time forge test -vvv --match-contract Invariant


