name: Foundry invariant tests

on: [pull_request]

jobs:
  invariant-tests:
    name: invariant-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Invariant Test Contracts
        run: time forge test -vvv --match-contract InvariantTest
